---
title: "Homework5"
author: "Susan Gogolski"
date: "2024-11-01"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(conflicted)
library(purrr)
library(scales)
library(tigris)
library(devtools)
library(forcats)
library(sf)
library(RColorBrewer)
```
```{r}
homicides <- read_csv("/Users/s/Desktop/Homework5/Homework5/data/homicide-data.csv")
```
```{r}
homicides$city_name <- paste(homicides$city, homicides$state, sep = ", ")
```
```{r}
location_Denver <- homicides %>%
  dplyr::filter(city_name == "Denver, CO") %>%
  dplyr::select(lon, lat, victim_race, disposition)
```
```{r}
location_Denver_one <- location_Denver %>%
  select(lon, lat, victim_race, disposition) 
```
```{r}
location_Denver_one$victim_race <- forcats::fct_infreq(location_Denver_one$victim_race)
```

```{r}
levels(location_Denver_one$victim_race)
```
```{r}
location_Denver_one$victim_race <- fct_lump_n(location_Denver_one$victim_race, n = 3, other_level = "Other")
```


```{r}
location_Denver_one$Solved <- ifelse(location_Denver_one$disposition == "Open/No arrest", "Unsolved", "Solved")
```

```{r}
co_counties <- counties(state = "CO", cb = TRUE, class = "sf")
class(co_counties)
```

```{r}
denver <- co_counties %>%
  dplyr::filter(NAME == "Denver")
denver
```
```{r}
denver_tracts <- tracts("CO", "Denver")
```
```{r}
ggplot() +
  geom_sf(data = denver, color = "lightgray", fill = "white") +
  geom_sf(data = denver_tracts, color = "darkgray", fill = NA, size = 0.3) +
  geom_point(data = location_Denver_one, mapping = aes(x = lon, y = lat, color = victim_race), 
             size = 0.7, alpha = 0.7) +
  facet_wrap(~Solved) +
  scale_color_brewer(palette = "Set1") +
  theme_void() +
  ggtitle("Number of homicides in Denver, CO") +
  theme(strip.text = element_text(size = 14, face = "bold"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 10),
        plot.title = element_text (size = 18, face = "bold", hjust = 0.5))
```






